// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEvxSnlcc1Sxw6wCM0o9dQWsQQbM1clw',
    appId: '1:628486625890:web:506244db8fef007e504f3b',
    messagingSenderId: '628486625890',
    projectId: 'propertiku-2daf5',
    authDomain: 'propertiku-2daf5.firebaseapp.com',
    storageBucket: 'propertiku-2daf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvtUTOazFdqdCM1LbJcVFBXTf72rkHkA',
    appId: '1:628486625890:android:103b7b56243a9446504f3b',
    messagingSenderId: '628486625890',
    projectId: 'propertiku-2daf5',
    storageBucket: 'propertiku-2daf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABq84ayJg5OzL_brQShlvSioG2K10UqRM',
    appId: '1:628486625890:ios:204646aed649df3e504f3b',
    messagingSenderId: '628486625890',
    projectId: 'propertiku-2daf5',
    storageBucket: 'propertiku-2daf5.appspot.com',
    iosClientId: '628486625890-647e645gome71gg1sfjkaq2dbeaojej6.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertiku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABq84ayJg5OzL_brQShlvSioG2K10UqRM',
    appId: '1:628486625890:ios:204646aed649df3e504f3b',
    messagingSenderId: '628486625890',
    projectId: 'propertiku-2daf5',
    storageBucket: 'propertiku-2daf5.appspot.com',
    iosClientId: '628486625890-647e645gome71gg1sfjkaq2dbeaojej6.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertiku',
  );
}
